### ISSUE TITLE
Not able to rename jobs.N.templates to instance_groups.N.jobs

### ISSUE THREAD

**Issue by qu1queee** [allomov/mantra#1]
Hi,

I find this tool really helpful for the v1 to v2 schema migration. I was testing the convertion, but I´m facing the following issue:

When defining my `transform.yml` file, the following is not working:

```
transforms:
- type: filter
  sections: ["jobs", "releases", "stemcells", "update"]
- type: rename
  section: "jobs"
  to: "instance_groups"
- type: rename <------------ this rename
  section: "instance_groups[].templates"
  to: "jobs"
```

and the error I see is:

```
/Users/poolk/.rvm/gems/ruby-2.4.1/gems/mantra-0.2.3/lib/mantra/transform/rename.rb:23:in `block in perform': parent should be a hash (Mantra::Transform::ValidationError)
```

Any ideas on this?
